name: CI/CD for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Distribute APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and package the app
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: 'testers'
          file: app/build/outputs/apk/debug/app-debug.apk